import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Dashboard } from './Dashboard';
import { BrowserView } from './BrowserView';
import { FlowEditor } from './FlowEditor';
import { ProjectView } from './ProjectView';
import { TaskScheduler } from './TaskScheduler';
import { GitHubView } from './GitHubView';
import { SettingsView } from './SettingsView';
import { DeployView } from './DeployView';
import { Marketplace } from './Marketplace';
import { MonacoEditor } from './MonacoEditor';
import { TerminalView } from './TerminalView';
import { FileExplorer } from './FileExplorer';
import { BottomTicker } from './BottomTicker';
import { Resizable } from './Resizable';
import { CheckCircle, FileText, Code2, Terminal, Folder } from 'lucide-react';
export const Workspace = ({ activeView, onNavigate, onSendMessage, setChatOpen, isMobile, editorTabs, activeTabPath, setActiveTabPath, activePanel, setActivePanel, terminalBlocks, openFile, mobileCodeView, setMobileCodeView }) => {
    const renderCodeView = () => {
        if (isMobile) {
            return (_jsxs("div", { className: "flex-1 flex flex-col min-h-0 relative bg-os-bg", children: [_jsxs("div", { className: "h-12 bg-os-panel border-b border-os-border flex items-center shrink-0 px-2 gap-2", children: [_jsx("div", { className: "flex-1 flex overflow-x-auto scrollbar-hide gap-1", children: editorTabs.map(tab => (_jsx("button", { onClick: () => setActiveTabPath(tab.path), className: `px-3 py-1.5 rounded-md text-xs whitespace-nowrap ${activeTabPath === tab.path ? 'bg-aussie-500/10 text-aussie-500 border border-aussie-500/30' : 'text-os-textDim'}`, children: tab.title }, tab.path))) }), _jsxs("div", { className: "flex bg-black/20 rounded-lg p-1 gap-1", children: [_jsx("button", { onClick: () => setMobileCodeView('editor'), className: `p-2 rounded ${mobileCodeView === 'editor' ? 'bg-white/10 text-white' : 'text-gray-500'}`, children: _jsx(Code2, { className: "w-4 h-4" }) }), _jsx("button", { onClick: () => setMobileCodeView('terminal'), className: `p-2 rounded ${mobileCodeView === 'terminal' ? 'bg-white/10 text-white' : 'text-gray-500'}`, children: _jsx(Terminal, { className: "w-4 h-4" }) }), _jsx("button", { onClick: () => setMobileCodeView('files'), className: `p-2 rounded ${mobileCodeView === 'files' ? 'bg-white/10 text-white' : 'text-gray-500'}`, children: _jsx(Folder, { className: "w-4 h-4" }) })] })] }), _jsxs("div", { className: "flex-1 relative overflow-hidden", children: [mobileCodeView === 'editor' && _jsx(MonacoEditor, { filePath: activeTabPath, language: editorTabs.find(t => t.path === activeTabPath)?.language || 'plaintext', isMobile: true }), mobileCodeView === 'terminal' && _jsx(TerminalView, { blocks: terminalBlocks, isMobile: true }), mobileCodeView === 'files' && _jsx(FileExplorer, { onFileClick: (path) => { openFile(path); setMobileCodeView('editor'); } })] })] }));
        }
        return (_jsxs("div", { className: "flex h-full w-full flex-row", children: [_jsxs("div", { className: "flex-1 flex flex-col min-w-0 border-r border-os-border", children: [_jsx("div", { className: "h-9 flex bg-os-bg border-b border-os-border shrink-0", children: _jsx("div", { className: "flex overflow-x-auto scrollbar-hide flex-1", children: editorTabs.map(tab => (_jsxs("div", { onClick: () => setActiveTabPath(tab.path), className: `flex items-center gap-2 px-4 min-w-[120px] max-w-[200px] cursor-pointer border-r border-os-border select-none text-[11px] relative group ${activeTabPath === tab.path ? 'bg-os-panel text-white font-medium' : 'text-os-textDim hover:bg-os-panel/50'}`, children: [activeTabPath === tab.path && _jsx("div", { className: "absolute top-0 left-0 right-0 h-[2px] bg-aussie-500" }), _jsx(FileText, { className: "w-3.5 h-3.5 opacity-70" }), _jsx("span", { className: "truncate flex-1", children: tab.title })] }, tab.path))) }) }), _jsx("div", { className: "flex-1 relative", children: _jsx(MonacoEditor, { filePath: activeTabPath, language: editorTabs.find(t => t.path === activeTabPath)?.language || 'plaintext' }) }), _jsx(Resizable, { direction: "vertical", mode: "next", reversed: true }), _jsxs("div", { className: "h-[280px] flex flex-col bg-os-bg shrink-0 border-t border-os-border", children: [_jsxs("div", { className: "h-8 flex items-center px-2 border-b border-os-border gap-4 bg-os-panel shrink-0", children: [_jsx("button", { onClick: () => setActivePanel('terminal'), className: `text-[10px] font-bold uppercase tracking-wider h-full px-2 border-b-2 ${activePanel === 'terminal' ? 'border-aussie-500 text-white' : 'border-transparent text-gray-500'}`, children: "Terminal" }), _jsx("button", { onClick: () => setActivePanel('problems'), className: `text-[10px] font-bold uppercase tracking-wider h-full px-2 border-b-2 ${activePanel === 'problems' ? 'border-aussie-500 text-white' : 'border-transparent text-gray-500'}`, children: "Problems" })] }), _jsx("div", { className: "flex-1 overflow-hidden relative", children: activePanel === 'terminal' ? _jsx(TerminalView, { blocks: terminalBlocks }) : _jsxs("div", { className: "flex items-center justify-center h-full text-gray-500 text-xs", children: [_jsx(CheckCircle, { className: "w-5 h-5 mr-2 text-aussie-500" }), "No problems found."] }) })] })] }), _jsx(Resizable, { direction: "horizontal", mode: "next", reversed: true }), _jsxs("div", { className: "w-[250px] flex flex-col bg-os-bg shrink-0 border-l border-os-border", children: [_jsx("div", { className: "h-9 flex bg-os-panel border-b border-os-border shrink-0 items-center px-3 text-[11px] font-bold uppercase tracking-wider text-gray-400", children: "Explorer" }), _jsx("div", { className: "flex-1 overflow-hidden relative", children: _jsx(FileExplorer, { onFileClick: openFile }) })] })] }));
    };
    return (_jsxs("div", { className: `flex-1 flex flex-col min-w-0 bg-os-bg relative overflow-hidden h-full`, children: [activeView === 'dashboard' && _jsx(Dashboard, { onNavigate: onNavigate, activeView: activeView }), activeView === 'browser' && _jsx(BrowserView, { onInteract: (q) => { onSendMessage(q); setChatOpen(true); } }), activeView === 'flow' && _jsx(FlowEditor, {}), activeView === 'projects' && _jsx(ProjectView, {}), activeView === 'scheduler' && _jsx(TaskScheduler, {}), activeView === 'github' && _jsx(GitHubView, {}), activeView === 'settings' && _jsx(SettingsView, {}), activeView === 'deploy' && _jsx(DeployView, {}), activeView === 'marketplace' && _jsx(Marketplace, {}), activeView === 'code' && renderCodeView(), !isMobile && _jsx(BottomTicker, {})] }));
};
